from .oplr_data_dependent_decay_auto_grad_torch import (
    oplr_data_dependent_decay_auto_grad_torch,
)
from .oplr_data_dependent_decay_torch import oplr_data_dependent_decay_torch
from .oplr_data_dependent_decay_triton import oplr_data_dependent_decay_triton
